import { createFileRoute } from "@tanstack/react-router";
import { runtimeEnv, supabasePublicConfig } from "../lib/runtime-env";
import { clearEmergencyCookie, createEmergencySession, emergencyCookie, readEmergencySession, verifyEmergencyCredentials } from "../lib/emergency-auth";

const ACCESS_COOKIE="zapflow_access_token";const REFRESH_COOKIE="zapflow_refresh_token";
function parseCookies(request:Request){const header=request.headers.get("cookie")||"";return Object.fromEntries(header.split(";").map(part=>part.trim()).filter(Boolean).map(part=>{const index=part.indexOf("=");return index===-1?[part,""]:[part.slice(0,index),decodeURIComponent(part.slice(index+1))];}));}
function isProduction(){return runtimeEnv("NODE_ENV")==="production";}
function cookie(name:string,value:string,maxAge:number){return `${name}=${encodeURIComponent(value)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${maxAge}${isProduction()?"; Secure":""}`;}
function clearCookie(name:string){return `${name}=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0${isProduction()?"; Secure":""}`;}
function emergencyProfile(session:{email:string;userId:string;organizationId:string;role:string}){return{authenticated:true,user:{id:session.userId,email:session.email},memberships:[{organization_id:session.organizationId,role:session.role}],activeOrganizationId:session.organizationId,authMode:"emergency-local"};}
async function getProfile(accessToken:string){const{url,key}=supabasePublicConfig();const headers={apikey:key,Authorization:`Bearer ${accessToken}`};const userResponse=await fetch(`${url}/auth/v1/user`,{headers});if(!userResponse.ok)return null;const user=await userResponse.json() as {id:string;email?:string};const membershipResponse=await fetch(`${url}/rest/v1/organization_members?user_id=eq.${encodeURIComponent(user.id)}&select=organization_id,role`,{headers});if(!membershipResponse.ok)throw new Error(`Falha ao carregar organizações: ${await membershipResponse.text()}`);const memberships=await membershipResponse.json() as {organization_id:string;role:string}[];return{user:{id:user.id,email:user.email||null},memberships};}
async function refreshSession(refreshToken:string){const{url,key}=supabasePublicConfig();const response=await fetch(`${url}/auth/v1/token?grant_type=refresh_token`,{method:"POST",headers:{apikey:key,"Content-Type":"application/json"},body:JSON.stringify({refresh_token:refreshToken})});if(!response.ok)return null;return await response.json() as {access_token:string;refresh_token:string;expires_in?:number};}
export const Route=createFileRoute("/api/auth")({server:{handlers:{
GET:async({request})=>{const emergency=await readEmergencySession(request);if(emergency)return Response.json(emergencyProfile(emergency));try{const cookies=parseCookies(request);let accessToken=cookies[ACCESS_COOKIE];let refreshed:{access_token:string;refresh_token:string;expires_in?:number}|null=null;let profile=accessToken?await getProfile(accessToken):null;if(!profile&&cookies[REFRESH_COOKIE]){refreshed=await refreshSession(cookies[REFRESH_COOKIE]);if(refreshed){accessToken=refreshed.access_token;profile=await getProfile(accessToken);}}if(!profile)return Response.json({authenticated:false},{status:401});const response=Response.json({authenticated:true,...profile,activeOrganizationId:profile.memberships[0]?.organization_id||null});if(refreshed){response.headers.append("Set-Cookie",cookie(ACCESS_COOKIE,refreshed.access_token,refreshed.expires_in||3600));response.headers.append("Set-Cookie",cookie(REFRESH_COOKIE,refreshed.refresh_token,60*60*24*30));}return response;}catch{return Response.json({authenticated:false},{status:401});}},
POST:async({request})=>{const body=await request.json() as {action?:"login"|"logout";email?:string;password?:string};if(body.action==="logout"){const response=Response.json({ok:true});response.headers.append("Set-Cookie",clearCookie(ACCESS_COOKIE));response.headers.append("Set-Cookie",clearCookie(REFRESH_COOKIE));response.headers.append("Set-Cookie",clearEmergencyCookie());return response;}if(body.action!=="login"||!body.email||!body.password)return Response.json({error:"E-mail e senha são obrigatórios"},{status:400});try{const{url,key}=supabasePublicConfig();const loginResponse=await fetch(`${url}/auth/v1/token?grant_type=password`,{method:"POST",headers:{apikey:key,"Content-Type":"application/json"},body:JSON.stringify({email:body.email.trim().toLowerCase(),password:body.password})});if(loginResponse.ok){const session=await loginResponse.json() as {access_token:string;refresh_token:string;expires_in?:number};const profile=await getProfile(session.access_token);if(profile?.memberships.length){const response=Response.json({ok:true,...profile,activeOrganizationId:profile.memberships[0].organization_id,authMode:"supabase"});response.headers.append("Set-Cookie",cookie(ACCESS_COOKIE,session.access_token,session.expires_in||3600));response.headers.append("Set-Cookie",cookie(REFRESH_COOKIE,session.refresh_token,60*60*24*30));return response;}}}catch{/* fallback below */}if(await verifyEmergencyCredentials(body.email,body.password)){const token=await createEmergencySession();const session=await readEmergencySession(new Request(request.url,{headers:{cookie:`zapflow_emergency_session=${encodeURIComponent(token)}`}}));const response=Response.json({ok:true,...(session?emergencyProfile(session):{}),authMode:"emergency-local"});response.headers.append("Set-Cookie",emergencyCookie(token));return response;}return Response.json({error:"E-mail ou senha inválidos"},{status:401});}
}}}});
