import { createFileRoute, useNavigate } from "@tanstack/react-router";
import {
  Activity, AlertTriangle, BarChart3, Bell, CalendarClock, CheckCircle2, ChevronDown,
  CircleHelp, ContactRound, FileText, Gauge, Inbox, Layers3, ListFilter, Menu,
  MessageCircle, MoreHorizontal, Plus, Search, Send, Settings, ShieldCheck,
  Smartphone, Sparkles, Users, WalletCards, Webhook, X, Zap,
} from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { WhatsAppSessionManager } from "../components/whatsapp-session-manager";
import { TemplatesPage } from "../components/templates-page";
import { getAuthState, listWhatsAppAccounts, logout, type WhatsAppAccount } from "../lib/zapflow-api";

export const Route = createFileRoute("/")({ component: ZapFlowApp });

type Section = "Dashboard" | "Campanhas" | "Contatos" | "Listas" | "Conversas" | "Templates" | "WhatsApp" | "Agendamentos" | "Relatórios" | "Logs" | "Equipe" | "Assinatura" | "Configurações";

const primaryNav: { label: Section; icon: typeof Gauge }[] = [
  { label: "Dashboard", icon: Gauge }, { label: "Campanhas", icon: Send }, { label: "Contatos", icon: ContactRound },
  { label: "Listas", icon: Layers3 }, { label: "Conversas", icon: Inbox }, { label: "Templates", icon: FileText },
  { label: "WhatsApp", icon: MessageCircle }, { label: "Agendamentos", icon: CalendarClock }, { label: "Relatórios", icon: BarChart3 }, { label: "Logs", icon: Activity },
];
const secondaryNav: { label: Section; icon: typeof Gauge }[] = [
  { label: "Equipe", icon: Users }, { label: "Assinatura", icon: WalletCards }, { label: "Configurações", icon: Settings },
];

function Logo() { return <div className="brand"><div className="brand-mark"><Zap size={20} strokeWidth={2.6}/></div><div><strong>ZapFlow</strong><span>Multi-session WhatsApp</span></div></div>; }
function StatusPill({ children, tone="neutral" }: { children: React.ReactNode; tone?: "neutral"|"warning"|"success" }) { return <span className={`status status-${tone}`}>{children}</span>; }
function Metric({ label,value,helper,icon:Icon }: { label:string;value:string;helper:string;icon:typeof Gauge }) { return <div className="metric-card"><div className="metric-top"><span>{label}</span><div className="metric-icon"><Icon size={18}/></div></div><strong>{value}</strong><small>{helper}</small></div>; }
function EmptyState({ icon:Icon,title,description,action }: { icon:typeof Gauge;title:string;description:string;action?:string }) { return <div className="empty-state"><div className="empty-icon"><Icon size={23}/></div><h3>{title}</h3><p>{description}</p>{action&&<button className="btn btn-primary"><Plus size={16}/>{action}</button>}</div>; }
function accountConnected(account: WhatsAppAccount) { const s=String(account.connection_status||account.session_status||account.status||"").toUpperCase(); return s.includes("CONNECTED")||s==="OPEN"; }

function Dashboard({ connected,onOpenWhatsApp }: { connected:number;onOpenWhatsApp:()=>void }) {
  return <><div className="page-heading"><div><span className="eyebrow">Visão geral</span><h1>Central de operações</h1><p>Controle sessões, campanhas, filas e respostas de todos os números em um único painel.</p></div><button className="btn btn-primary"><Plus size={17}/>Nova campanha</button></div>
    <div className="metrics-grid"><Metric label="Números conectados" value={`${connected}/10`} helper="Sessões reais confirmadas" icon={Smartphone}/><Metric label="Enviadas hoje" value="0" helper="Aguardando primeira campanha" icon={Send}/><Metric label="Respostas" value="0" helper="Inbox ainda sem conversas" icon={MessageCircle}/><Metric label="Falhas" value="0" helper="Nenhuma falha registrada" icon={AlertTriangle}/></div>
    <div className="dashboard-grid"><section className="panel panel-main"><div className="panel-title"><div><span className="eyebrow">Primeiros passos</span><h2>Prepare sua operação</h2></div><StatusPill tone={connected?"success":"warning"}>{connected?"Gateway ativo":"Configuração em andamento"}</StatusPill></div><div className="setup-list">
      <div className="setup-row"><div className="setup-index done"><CheckCircle2 size={17}/></div><div><strong>Autenticação e isolamento</strong><span>Sessão protegida, organizações e permissões Owner/Admin ativas.</span></div><StatusPill tone="success">Pronto</StatusPill></div>
      <div className="setup-row"><div className={`setup-index ${connected?"done":""}`}>{connected?<CheckCircle2 size={17}/>:2}</div><div><strong>Gateway Evolution/Baileys</strong><span>QR, status, logout e exclusão são executados somente pelo backend autenticado.</span></div><StatusPill tone={connected?"success":"warning"}>{connected?"Conectado":"Aguardando sessão"}</StatusPill></div>
      <div className="setup-row"><div className="setup-index">3</div><div><strong>Conectar até 10 números</strong><span>Cada número possui sessão independente e pode ser gerenciado pelo painel.</span></div><button className="btn btn-soft" onClick={onOpenWhatsApp}>Abrir WhatsApp</button></div>
      <div className="setup-row"><div className="setup-index done"><CheckCircle2 size={17}/></div><div><strong>Fila persistente e balanceada</strong><span>Jobs são divididos igualmente entre todas as sessões conectadas, com consentimento, deduplicação, pacing e retry controlado.</span></div><StatusPill tone="success">Ativa</StatusPill></div>
    </div></section><section className="panel health-card"><div className="panel-title"><div><span className="eyebrow">Sessões</span><h2>Saúde do gateway</h2></div><Webhook size={19}/></div><div className="health-score"><div className="score-ring"><span>{connected}</span></div><div><strong>{connected?"Sessões confirmadas pelo gateway":"Nenhuma sessão conectada"}</strong><p>Somente sessões realmente conectadas participam da distribuição.</p></div></div><div className="health-lines"><span><i className="dot ok"/>Autenticação Supabase</span><span><i className={connected?"dot ok":"dot wait"}/>Gateway de sessões</span><span><i className="dot ok"/>Distribuição balanceada</span></div></section></div>
    <section className="panel"><div className="panel-title"><div><span className="eyebrow">Campanhas</span><h2>Proteções operacionais</h2></div></div><div className="p-4 text-sm leading-6 text-[#526158]">Contatos sem consentimento, suprimidos, inválidos ou duplicados são rejeitados antes da fila. O envio direto foi desativado para que campanhas reais sempre passem pelo processamento persistente e espaçado.</div></section></>;
}

function CampaignsPage({ accounts }: { accounts:WhatsAppAccount[] }) {
  const active=accounts.filter(accountConnected);
  const [previewTotal,setPreviewTotal]=useState(103);
  const safeTotal=Math.max(0,Math.min(Number.isFinite(previewTotal)?previewTotal:0,5000));
  const allocation=active.length?active.map((account,index)=>({account,jobs:Math.floor(safeTotal/active.length)+(index<safeTotal%active.length?1:0)})):[];
  const values=allocation.map(item=>item.jobs);
  const difference=values.length?Math.max(...values)-Math.min(...values):0;
  return <><div className="page-heading"><div><span className="eyebrow">Operação</span><h1>Campanhas</h1><p>Campanhas reais são persistidas e divididas igualmente entre todas as sessões conectadas.</p></div><button className="btn btn-primary"><Plus size={17}/>Nova campanha</button></div><div className="filterbar"><div className="search"><Search size={17}/><input placeholder="Buscar campanha..."/></div><button className="btn btn-soft"><ListFilter size={16}/>Filtros</button></div>
    <section className="panel mb-4"><div className="panel-title"><div><span className="eyebrow">Distribuidor equilibrado</span><h2>Prévia da divisão</h2></div><StatusPill tone={active.length?"success":"warning"}>{active.length} sessões ativas</StatusPill></div><div className="flex flex-wrap items-end gap-3 border-b border-[#edf1ee] p-4"><label className="grid gap-1 text-xs font-semibold text-[#66756b]">Quantidade de destinatários<input type="number" min={0} max={5000} value={previewTotal} onChange={e=>setPreviewTotal(Math.max(0,Math.min(5000,Number(e.target.value)||0)))} className="h-10 w-44 rounded-xl border border-[#dfe7e1] px-3 text-sm outline-none"/></label><div className="text-xs text-[#718077]">Diferença máxima entre números: <strong>{difference}</strong> mensagem. A fila real usa o mesmo round-robin.</div></div>{active.length?<div className="grid grid-cols-2 gap-3 p-4 max-[700px]:grid-cols-1">{allocation.map(({account,jobs})=><div key={account.id} className="flex items-center justify-between rounded-xl border border-[#e5ebe6] p-4"><div><strong className="block text-sm text-[#2a3c30]">{account.internal_name||account.session_id}</strong><span className="mt-1 block text-[11px] text-[#87958c]">{account.phone||"Telefone conectado"}</span></div><strong className="text-lg text-[#159447]">{jobs} jobs</strong></div>)}</div>:<EmptyState icon={Smartphone} title="Nenhuma sessão ativa" description="Conecte pelo menos um número real antes de criar a distribuição da campanha."/>}</section>
    <section className="panel"><div className="p-4 text-sm leading-6 text-[#526158]"><strong className="text-[#304237]">Controles ativos:</strong> consentimento obrigatório, supressão respeitada, telefone normalizado, deduplicação por número, distribuição igualitária, espaçamento mínimo por sessão, fila persistente e retry com backoff. Nenhuma configuração consegue garantir que uma plataforma nunca aplique restrições; esses controles servem para uma operação mais responsável.</div></section></>;
}

function ContactsPage(){return <><div className="page-heading"><div><span className="eyebrow">Base de contatos</span><h1>Contatos</h1><p>Importe contatos, normalize telefones e mantenha registro de consentimento e supressão.</p></div><div className="actions"><button className="btn btn-soft">Importar arquivo</button><button className="btn btn-primary"><Plus size={17}/>Adicionar contato</button></div></div><div className="mini-metrics"><div><span>Total</span><strong>0</strong></div><div><span>Opt-in</span><strong>0</strong></div><div><span>Opt-out</span><strong>0</strong></div><div><span>Bloqueados</span><strong>0</strong></div></div><section className="panel"><EmptyState icon={ContactRound} title="Nenhum contato cadastrado" description="Importe TXT, CSV ou XLSX. Contatos sem autorização não entram automaticamente em campanhas." action="Importar contatos"/></section></>}

function GenericPage({section}:{section:Exclude<Section,"Dashboard"|"Campanhas"|"Contatos"|"Templates"|"WhatsApp">}){const map:Record<typeof section,[typeof Gauge,string,string,string]>={Listas:[Layers3,"Listas de contatos","Crie segmentos reutilizáveis e associe listas a remetentes específicos.","Criar lista"],Conversas:[Inbox,"Inbox","Centralize respostas recebidas de todos os números conectados.","Nenhuma conversa recebida"],Agendamentos:[CalendarClock,"Agendamentos","Programe campanhas e janelas de processamento no backend.","Criar agendamento"],Relatórios:[BarChart3,"Relatórios","Compare desempenho por campanha, lista e número remetente.","Nenhum dado para analisar"],Logs:[Activity,"Logs operacionais","Acompanhe sessão, fila, envio, falha e reconexão sem expor segredos.","Nenhum evento registrado"],Equipe:[Users,"Equipe","Gerencie Owner, Admin, Manager, Operator e Viewer.","Convidar membro"],Assinatura:[WalletCards,"Assinatura","Controle limites de sessões e recursos por plano.","Gerenciar plano"],Configurações:[Settings,"Configurações","Configure gateway, segurança, notificações e comportamento das filas.","Configurar workspace"]};const[Icon,title,description,action]=map[section];return <><div className="page-heading"><div><span className="eyebrow">ZapFlow</span><h1>{title}</h1><p>{description}</p></div><button className="btn btn-primary"><Plus size={17}/>{action}</button></div><section className="panel"><EmptyState icon={Icon} title={section==="Conversas"||section==="Relatórios"||section==="Logs"?action:`Nenhum item em ${title.toLowerCase()}`} description="Esta área começa vazia e será alimentada somente por dados reais da sua organização."/></section></>}

function ZapFlowApp(){
  const navigateRouter=useNavigate(); const[section,setSection]=useState<Section>("Dashboard"); const[mobileOpen,setMobileOpen]=useState(false); const[organizationId,setOrganizationId]=useState<string|null>(null); const[email,setEmail]=useState<string|null>(null); const[role,setRole]=useState("OWNER"); const[accounts,setAccounts]=useState<WhatsAppAccount[]>([]); const[loadingAuth,setLoadingAuth]=useState(true); const title=useMemo(()=>section,[section]); const connected=accounts.filter(accountConnected).length;
  useEffect(()=>{getAuthState().then(async auth=>{if(!auth.activeOrganizationId){navigateRouter({to:"/login"});return;}setOrganizationId(auth.activeOrganizationId);setEmail(auth.user.email);setRole(auth.memberships.find(m=>m.organization_id===auth.activeOrganizationId)?.role||"MEMBER");try{const response=await listWhatsAppAccounts(auth.activeOrganizationId);setAccounts(response.accounts||[]);}catch{}setLoadingAuth(false);}).catch(()=>navigateRouter({to:"/login"}));},[navigateRouter]);
  async function refreshAccounts(){if(!organizationId)return;try{const response=await listWhatsAppAccounts(organizationId);setAccounts(response.accounts||[]);}catch{}}
  async function signOut(){await logout().catch(()=>undefined);navigateRouter({to:"/login"});}
  const navigate=(label:Section)=>{setSection(label);setMobileOpen(false);if(label!=="WhatsApp")void refreshAccounts();};
  if(loadingAuth)return <main className="grid min-h-screen place-items-center bg-[#f4f7f4] text-[#526158]"><div className="text-center"><Zap size={30} className="mx-auto mb-3 text-[#269451]"/><strong>Carregando ZapFlow...</strong></div></main>;
  if(!organizationId)return null;
  const initials=(email||"ZF").split("@")[0].slice(0,2).toUpperCase();
  const genericSection = !(["Dashboard","Campanhas","Contatos","Templates","WhatsApp"] as Section[]).includes(section) ? section as Exclude<Section,"Dashboard"|"Campanhas"|"Contatos"|"Templates"|"WhatsApp"> : null;
  return <div className="app-shell"><aside className={`sidebar ${mobileOpen?"open":""}`}><div className="sidebar-top"><Logo/><button className="mobile-close" onClick={()=>setMobileOpen(false)}><X size={20}/></button></div><div className="workspace-switch"><div className="workspace-avatar">Z</div><div><span>Workspace</span><strong>ZapFlow</strong></div><ChevronDown size={16}/></div><nav>{primaryNav.map(({label,icon:Icon})=><button key={label} className={section===label?"active":""} onClick={()=>navigate(label)}><Icon size={18}/><span>{label}</span></button>)}</nav><div className="nav-divider"/><nav>{secondaryNav.map(({label,icon:Icon})=><button key={label} className={section===label?"active":""} onClick={()=>navigate(label)}><Icon size={18}/><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><div className="help-card"><Sparkles size={18}/><strong>Sessões WhatsApp</strong><span>{connected?`${connected} número(s) conectado(s) ao gateway.`:"Conecte o primeiro número por QR."}</span><button onClick={()=>navigate("WhatsApp")}>Gerenciar sessões</button></div><button className="account-row" onClick={()=>void signOut()} title="Sair"><div className="avatar">{initials}</div><div><strong>{email||"Minha conta"}</strong><span>{role} • clique para sair</span></div><MoreHorizontal size={17}/></button></div></aside>{mobileOpen&&<button className="scrim" onClick={()=>setMobileOpen(false)} aria-label="Fechar menu"/>}<main className="main-area"><header className="topbar"><div className="topbar-left"><button className="mobile-menu" onClick={()=>setMobileOpen(true)}><Menu size={21}/></button><div><span>ZapFlow</span><strong>{title}</strong></div></div><div className="topbar-actions"><div className="global-search"><Search size={16}/><span>Buscar</span><kbd>⌘ K</kbd></div><button className="icon-btn"><CircleHelp size={19}/></button><button className="icon-btn notification"><Bell size={19}/><i/></button><button className="profile-btn" onClick={()=>void signOut()} title="Sair">{initials}</button></div></header><div className="content-wrap">{section==="Dashboard"&&<Dashboard connected={connected} onOpenWhatsApp={()=>navigate("WhatsApp")}/>} {section==="Campanhas"&&<CampaignsPage accounts={accounts}/>} {section==="Contatos"&&<ContactsPage/>} {section==="Templates"&&<TemplatesPage organizationId={organizationId}/>} {section==="WhatsApp"&&<WhatsAppSessionManager organizationId={organizationId} onConnectedCountChange={()=>void refreshAccounts()}/>} {genericSection&&<GenericPage section={genericSection}/>}<footer className="app-footer"><span><ShieldCheck size={12}/>ZapFlow • backend multi-tenant</span><span>10 sessões por organização</span></footer></div></main></div>;
}
